### ISSUE TITLE
Antonio Carbajal missing on Player_Appearences table

### ISSUE THREAD

**Issue by glasneed** [jfjelstul/worldcup#4]
Hi,
I noticed that Mexican goalkeeper, Antonio Carbajal, is missing on the player_appearences table. He is on the players table and shows that he played in 5 tournaments which is correct.

https://www.thesoccerworldcups.com/players/antonio_carbajal.php

`SELECT 
       player_id,
       position_name  
FROM 
       player_appearances
  where player_id IN
  (SELECT player_ID from players where family_name = 'Carbajal')`

**Comment by jfjelstul** [comment]
Thanks for using the data! 

`player_appearances` starts in 1970 and Carbajal's last tournament was 1966, so that's why he doesn't appear. But he does appear in `squads`, which goes back to 1930. That's why `list_tournaments` in `players` is still correct.

I'll look into collecting earlier data. The problem is that `player_appearances` includes starters and subs, and information on subs isn't consistently available before 1970.

**Comment by glasneed** [comment]
Thank you for the clarification. I guess I should have read the first line in the code book for player appearances. 
It came up because I was solving a challenge for 'players for the most tournaments played'. I found this table to be the best source because, for example, Gianluigi Buffon played in 4 tournaments but 'attended' 5. When I relied on this table and didn't return Antonio Carbajal, I opened the ticket. 
Fantastic dataset BTW!!

**Comment by glasneed** [comment]
Thank you for the clarification. I guess I should have read the first line in the code book for player_appearances. 
It came up because I was solving a challenge for 'players for the most tournaments played'. I found this table to be the best source because, for example, Gianluigi Buffon played in 4 tournaments but 'attended' 5. When I relied on this table and didn't return Antonio Carbajal, I opened the ticket. 
Fantastic dataset BTW!!
