### ISSUE TITLE
Codebook versus SQLite table - Different number of variables for Goals table

### ISSUE THREAD

**Issue by glasneed** [jfjelstul/worldcup#5]
The codebook lists 27 variables, the SQLite table shows 15 columns. For example, there is no family_name in the SQLite version but it is referenced in the code book.
![goals](https://user-images.githubusercontent.com/26227953/208247421-b2b9dadc-3592-47cd-89bd-a20c18f98806.jpg)

**Comment by jfjelstul** [comment]
This is intentional. Each table in the database has a different unit of observation, but in the `.csv` version, I've pre-merged in relevant variables from other tables for convenience. The codebook is based on the `.csv` version. Since the `SQLite` version is a relational database, tables don't include variables that vary according to a different unit of observation. Each table in the `SQLite` database has a primary key that uniquely identifies each observation. And then some tables also have foreign keys, which map each observation to observations in other tables. You can merge tables together based on these foreign keys. The file `data-sqlite/SQL-schema.txt` indicates which variables in each table are foreign keys.

**Comment by glasneed** [comment]
Thank you for the clarification on this.
